title: "Francesco Amendola"
description: "Senior Android Developer & IT Teacher"
#theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/images/profile-pic-512.jpg
show_downloads: false

markdown: kramdown
kramdown:
  input: GFM

url: "https://amendolafr.github.io/"
baseurl: ""

author:
  name: "Francesco Amendola"
  email: "amendola.fr@outlook.com"
  location: "Italy"
  linkedin: "https://www.linkedin.com/in/francesco-amendola"
